//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument
ext {
    moduleName = 'exception-library-api'
}

apply from: "${rootDir}/${rootProject.configurationPath}/shared-gradle-files/standard-module.gradle"

dependencies {
    implementation 'org.springframework:spring-web:' + rootProject.dependencyVersions.springframeworkSpringWebVersion
}